### ISSUE TITLE
How to improve the computational cost of MAP estimation

### ISSUE THREAD

**Issue by claudia-lat** [claudia-lat/MAPest#17]
I started working on how to improve the computational cost in MAP estimation with the commit d560b775ea62f88b8e751e4d83dad4ac5a7749c3. Since most of the code time is spent on the inversion of the _Sigma_dgiveny_ matrix,  I ran `main.m` by considering 50 samples and by writing different code in `MAPcomputation.m`
## CASE 1:

![screen shot 2016-10-28 at 16 57 58](https://cloud.githubusercontent.com/assets/10923418/19810990/e286ad70-9d2f-11e6-9b23-08d47325150e.png)
and this is what the profile analysis gave me:
![screen shot 2016-10-28 at 16 38 00](https://cloud.githubusercontent.com/assets/10923418/19810236/fa1e41d0-9d2c-11e6-91a1-f01feebaa9ef.png)
## CASE 2:

![screen shot 2016-10-28 at 16 58 24](https://cloud.githubusercontent.com/assets/10923418/19811090/458a6286-9d30-11e6-8d0a-5b27501c399e.png)
![screen shot 2016-10-28 at 16 54 51](https://cloud.githubusercontent.com/assets/10923418/19811117/5e5b3736-9d30-11e6-8493-e156ec93d1dd.png)
## CASE 3:

![screen shot 2016-10-28 at 16 59 01](https://cloud.githubusercontent.com/assets/10923418/19811125/6e0cd9c8-9d30-11e6-840f-e48f306589f3.png)
![screen shot 2016-10-28 at 16 51 54](https://cloud.githubusercontent.com/assets/10923418/19811135/74d850ca-9d30-11e6-8a3e-af3adfa12e86.png)

**Comment by claudia-lat** [comment]
@traversaro

**Comment by MariaLazzaroni** [comment]
In order to improve the computational cost of MAP estimation, I ran the _MAPcomputation.m_ function in three different cases:

## **CASE 1:** 
~~~matlab
mu_dgiveny(:,i) = (SigmaBarD_inv + Y' * Sigmay_inv * Y)\(Y' * (Sigmay_inv * (y(:,i) - b_Y))
                 + SigmaBarD_inv * muBarD);
~~~

![mapnormale](https://cloud.githubusercontent.com/assets/14000095/22244034/354ba26a-e22a-11e6-9668-5281d36b7391.png)

## **CASE 2:**
with Cholesky decomposition, then forward substitution and finally back substitution
### without permutation:
~~~matlab
C             = (SigmaBarD_inv + Y' * Sigmay_inv * Y);
[R]           = chol(C);  % R is such that R'*R = C

g             = (Y' * (Sigmay_inv * (y(:,i) - b_Y)) + SigmaBarD_inv * muBarD);
z_forward     = R'\g;
mu_dgiveny(:,i)   = R\z_forward;
~~~

![1cholwithoutp](https://cloud.githubusercontent.com/assets/14000095/22248810/af55c3a4-e240-11e6-9521-0e0da11ef52f.png)

### with permutation:
~~~matlab
C1            = (SigmaBarD_inv + Y' * Sigmay_inv * Y); %Sigma_dgiveny
C             = P'*C1*P; % P is given as input 
[R]           = chol(C);  % R is such that R'*R = P'*C*P

g             = (Y' * (Sigmay_inv * (y(:,i) - b_Y)) + SigmaBarD_inv * muBarD);
w_forward     = P\g;
z_forward     = R'\w_forward;
y_forward     = R\z_forward;
mu_dgiveny(:,i)= P'\y_forward;
~~~

![1cholwithp](https://cloud.githubusercontent.com/assets/14000095/22248741/59659140-e240-11e6-9038-5521ac20ee16.png)

## **CASE 3:**
Cholesky decomposition to solve not only mu_dgiveny but also muBarD
### without permutation:
~~~matlab
muBarD = myCholSolve(SigmaBarD_inv , Sigmad_inv * mud - D' * (SigmaD_inv * b_D));
mu_dgiveny(:,i) = myCholSolve(SigmaBarD_inv + Y' * Sigmay_inv * Y ,
                     Y' * (Sigmay_inv * (y(:,i) - b_Y)) + SigmaBarD_inv * muBarD);

function [x] = myCholSolve(A, b)
    [R]           = chol(A); % R is such that R'*R = A

    z_forward     = R'\b;
    x             = R\z_forward;
end
~~~

![2cholwithoutp](https://cloud.githubusercontent.com/assets/14000095/22248918/1ec5ebba-e241-11e6-90ad-9b7612e14246.png)

### with permutation:
~~~matlab
muBarD = myCholSolve(SigmaBarD_inv , Sigmad_inv * mud - D' * (SigmaD_inv * b_D) , PsigmaBar);
mu_dgiveny(:,i) = myCholSolve(SigmaBarD_inv + Y' * Sigmay_inv * Y , 
                     Y' * (Sigmay_inv * (y(:,i) - b_Y)) + SigmaBarD_inv * muBarD , P);

function [x] = myCholSolve(A, b, P)
    C             = P'*A*P; % P is given as input 
    [R]           = chol(C); % R is such that R'*R = P'*C*P
    
    w_forward     = P\b;
    z_forward     = R'\w_forward;
    y_forward     = R\z_forward;
    x             = P'\y_forward;
end
~~~

![2cholwithp](https://cloud.githubusercontent.com/assets/14000095/22248871/ee963b8e-e240-11e6-8069-d53efe95af32.png)

**Comment by francesco-romano** [comment]
cc @iron76

**Comment by francesco-romano** [comment]
With the code in https://github.com/robotology/idyntree/pull/261 this is the output of the profiler.

Baseline (i.e. code in iDynTree master)

![master2](https://cloud.githubusercontent.com/assets/2189180/22787365/55219360-eedc-11e6-996b-d4334cb369da.png)

iDynTree PR

![screen shot 2017-02-09 at 13 39 51](https://cloud.githubusercontent.com/assets/2189180/22787371/5d9f0ca2-eedc-11e6-948f-51f7008db78e.png)

**Comment by claudia-lat** [comment]
Close after the merging of pull request #21.
@MariaLazzaroni @francesco-romano

**Comment by claudia-lat** [comment]
I consider this issue solved by the merging of the pull request https://github.com/claudia-lat/MAPest/pull/21 .
@MariaLazzaroni  @francesco-romano
